apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  template:
    metadata:
      name: department-service-app
      labels:
        app: department-service-app
    spec:
      containers:
        - name: department-service-app
          image: hjaiejhoussem/department-service:1-slim
          ports:
            - containerPort: 9001
      restartPolicy: Always
  selector:
    matchLabels:
      app: department-service-app
---

apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
spec:
  selector:
    app: department-service-app
  ports:
    - port: 80
      targetPort: 9001
  type: ClusterIP
