apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_adress: http://eureka-0.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  labels:
    app:
spec:
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: hjaiejhoussem/service-registry:1-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: eureka_service_adress
                  name: eureka-cm
      restartPolicy: Always
  selector:
    matchLabels:
      app: eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: 8761
  type: NodePort
